# Generated by Django 2.2.1 on 2020-02-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_text',
            fields=[
                ('Wid', models.IntegerField(primary_key=True, serialize=False)),
                ('Wtext', models.TextField()),
                ('Wdate', models.DateTimeField()),
            ],
        ),
    ]
