# Generated by Django 2.2.1 on 2020-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_text',
            name='Wdate',
        ),
        migrations.AddField(
            model_name='web_text',
            name='WFloorCount',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='web_text',
            name='Wid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='web_text',
            name='Wtext',
            field=models.TextField(default="cong's forum"),
        ),
    ]
