# Generated by Django 2.2.1 on 2020-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0002_auto_20200207_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_text',
            name='Wpic',
            field=models.ImageField(default='null', upload_to='img'),
        ),
        migrations.AddField(
            model_name='web_text',
            name='WpicName',
            field=models.ImageField(default='empty', upload_to=''),
        ),
    ]
