# Generated by Django 2.2.1 on 2020-02-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0004_auto_20200217_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_text',
            name='Wpic',
            field=models.ImageField(default='null', upload_to='img'),
        ),
    ]
