# Generated by Django 2.2.1 on 2020-02-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0007_web_pic_web_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_range',
            name='WRanPath',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
