# Generated by Django 2.2.1 on 2020-02-18 11:46

from django.db import migrations, models
import train_pic.models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0008_auto_20200218_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_pic',
            name='Wpic',
            field=models.ImageField(default='null', upload_to=train_pic.models.individualPath),
        ),
    ]
