# Generated by Django 2.2.1 on 2020-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_pic', '0009_auto_20200218_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_pic',
            name='WpicName',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
