# Generated by Django 2.2.1 on 2020-02-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Ttype', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=30)),
                ('S_first_date', models.DateTimeField()),
                ('S_num', models.IntegerField()),
                ('S_pic', models.BinaryField()),
                ('S_usedfor', models.NullBooleanField(db_column='0货运,1客运,null客货两用')),
                ('S_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mix_forum.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=30)),
                ('E_first_date', models.DateTimeField()),
                ('E_num', models.IntegerField()),
                ('E_pic', models.BinaryField()),
                ('E_usedfor', models.NullBooleanField(db_column='0货运,1客运,null客货两用')),
                ('E_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mix_forum.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Diesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=30)),
                ('D_first_date', models.DateTimeField()),
                ('D_num', models.IntegerField()),
                ('D_pic', models.BinaryField()),
                ('D_usedfor', models.NullBooleanField(db_column='0货运,1客运,null客货两用')),
                ('D_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mix_forum.Train')),
            ],
        ),
    ]
